/* Biblioteca procedural Macroservice V5.5
   Procedimentos são referências operacionais. Torques, fluidos, folgas, sequências,
   boletins e especificações devem ser confirmados no manual técnico do veículo. */
(function(){
  const common={
    safety:["Confirmar veículo, placa/VIN e serviço solicitado.","Usar EPI adequado e estabilizar o veículo antes de trabalhar.","Desconectar a bateria quando o procedimento elétrico/mecânico exigir.","Seguir torques, fluidos e sequências do fabricante."],
    finish:["Realizar inspeção final da área trabalhada.","Apagar falhas somente quando aplicável e após confirmar a causa.","Executar teste funcional/rodagem quando seguro.","Registrar medições, peças utilizadas e recomendações no relatório."]
  };

  const catTools={
    "Motor":["jogo de soquetes e chaves","torquímetro","scanner automotivo","multímetro","ferramentas de sincronismo conforme motor"],
    "Ignição":["scanner","multímetro","osciloscópio/diagnóstico quando disponível","soquete de vela","torquímetro"],
    "Injeção Eletrônica / Combustível":["scanner","multímetro","manômetro de combustível","máquina de teste de bicos quando aplicável","alicates e adaptadores"],
    "Arrefecimento":["testador de pressão","termômetro/scan data","ferramentas manuais","coletor para fluido"],
    "Lubrificação":["manômetro de pressão de óleo","soquetes/chaves","torquímetro","bandeja coletora"],
    "Embreagem":["elevador/cavaletes","macaco de transmissão","jogo de soquetes","torquímetro","centralizador de embreagem"],
    "Câmbio / Transmissão":["elevador","macaco de transmissão","jogo de soquetes","torquímetro","extratores conforme aplicação"],
    "Suspensão":["elevador","jogo de soquetes","torquímetro","saca-pivô/extrator","compressor de mola quando aplicável"],
    "Direção":["elevador","soquetes/chaves","torquímetro","ferramenta de terminal/axial","scanner para EPS quando necessário"],
    "Freios":["elevador","soquetes/chaves","torquímetro","recuador de pistão","equipamento de sangria"],
    "Elétrica / Eletrônica":["multímetro","scanner","lâmpada de prova adequada","alicate amperímetro","diagrama elétrico"],
    "Ar-condicionado":["manifold","estação de A/C","bomba de vácuo","detector de vazamento","termômetro"],
    "Alinhamento / Geometria":["alinhador computadorizado","rampa/plataforma","ferramentas de ajuste","calibrador de pneus"],
    "Balanceamento / Rodas":["balanceadora","desmontadora quando aplicável","torquímetro de roda","calibrador"],
    "Rodas / Pneus / Borracharia":["desmontadora","vulcanizador/reparo apropriado","calibrador","torquímetro de roda"],
    "Lavagem / Higienização":["lavadora","aspirador/extratora","produtos adequados","pincéis e panos de microfibra"],
    "Revisão":["checklist de revisão","scanner","multímetro","calibrador","ferramentas manuais"]
  };

  const packs=[
    {re:/compress[aã]o/i, title:"Medição de compressão", tools:["compressímetro","carregador de bateria"], steps:["Aquecer o motor quando a condição permitir e confirmar carga da bateria.","Desabilitar injeção/ignição para evitar partida do motor.","Remover as velas e instalar o compressímetro no cilindro 1.","Manter borboleta aberta quando o fabricante recomendar e acionar a partida por ciclos uniformes.","Registrar a pressão máxima de cada cilindro e repetir o mesmo número de giros.","Comparar cilindros entre si e com a especificação técnica do motor.","Se houver diferença, complementar com teste úmido ou leak-down para localizar a perda."], checks:["Uniformidade entre cilindros","Pressão dentro da especificação","Condição de bateria/rotação de partida"]},
    {re:/estanqueidade|leak.?down/i,title:"Teste de estanqueidade dos cilindros",tools:["leak-down tester","compressor de ar"],steps:["Posicionar o cilindro em PMS de compressão.","Travar o virabrequim com segurança conforme necessário.","Regular o equipamento e aplicar ar comprimido.","Registrar percentual de fuga.","Escutar admissão, escape, cárter e observar reservatório para localizar a perda.","Repetir em todos os cilindros e comparar resultados."],checks:["Percentual de fuga","Origem da fuga","Comparação entre cilindros"]},
    {re:/press[aã]o de [oó]leo/i,title:"Medição de pressão de óleo",tools:["manômetro de pressão de óleo","adaptadores de rosca","termômetro/scan data"],steps:["Confirmar nível, viscosidade e condição do óleo.","Remover o interruptor/sensor e instalar o manômetro adequado.","Dar partida e verificar vazamentos no adaptador.","Medir com motor frio e depois na temperatura normal de trabalho.","Registrar pressão em marcha lenta e nas rotações especificadas.","Comparar com a especificação do fabricante antes de condenar bomba ou mancais."],checks:["Pressão em lenta","Pressão em rotação","Temperatura do óleo/motor","Nível e viscosidade do lubrificante"]},
    {re:/vaz[aã]o da bomba|press[aã]o da linha de combust[ií]vel|teste da bomba de combust/i,title:"Teste do sistema de combustível",tools:["manômetro de combustível","medidor de vazão","multímetro"],steps:["Aliviar pressão do sistema com segurança.","Instalar manômetro no ponto correto e verificar estanqueidade.","Acionar a bomba e registrar pressão inicial e residual.","Com motor em funcionamento, observar pressão em lenta e sob carga quando aplicável.","Medir vazão em intervalo controlado se o procedimento exigir.","Verificar alimentação elétrica, aterramento e queda de tensão da bomba antes de condená-la."],checks:["Pressão estática","Pressão dinâmica","Pressão residual","Vazão","Tensão e aterramento da bomba"]},
    {re:/bicos? injetor|pulveriza[cç][aã]o|equaliza[cç][aã]o/i,title:"Teste e manutenção de bicos injetores",tools:["máquina de limpeza/teste de bicos","multímetro","equipamento ultrassônico","kit de reparo/vedações"],steps:["Despressurizar o sistema e remover flauta/bicos conforme o veículo.","Inspecionar conectores, O-rings e contaminação.","Medir resistência elétrica quando aplicável.","Executar teste de estanqueidade, padrão de pulverização e equalização.","Realizar limpeza ultrassônica/retro-lavagem quando adequada.","Repetir medições e comparar volumes.","Instalar com vedações adequadas e testar vazamentos."],checks:["Estanqueidade","Equalização de vazão","Padrão de pulverização","Vedação após montagem"]},
    {re:/correia dentada|sincronismo do motor|kit correia/i,title:"Serviço de sincronismo",tools:["kit de sincronismo específico","torquímetro","soquetes/chaves","ferramenta de tensão conforme aplicação"],steps:["Confirmar motor/código e procedimento técnico correto.","Desconectar bateria quando recomendado e remover proteções/acessórios necessários.","Posicionar motor nas referências de sincronismo e instalar ferramentas de travamento.","Remover tensor/correia e inspecionar polias, retentores e bomba d'água quando acionada pelo conjunto.","Instalar componentes novos respeitando sentido, tensão e sequência.","Aplicar torques especificados.","Girar o motor manualmente pelo número de voltas recomendado e conferir novamente as marcas.","Montar proteções, dar partida e verificar ruídos/fugas."],checks:["Marcas de sincronismo","Tensão da correia","Torques","Ausência de ruído e vazamento"]},
    {re:/troca de [oó]leo|[oó]leo e filtro|filtro de [oó]leo/i,title:"Troca de óleo e filtro",tools:["chave de filtro","bandeja coletora","torquímetro","funil"],steps:["Confirmar especificação, viscosidade, norma e capacidade do motor.","Aquecer levemente o motor e elevar o veículo com segurança.","Drenar o óleo e inspecionar bujão/arruela.","Substituir o filtro e lubrificar a vedação quando aplicável.","Reinstalar bujão com torque especificado.","Abastecer volume inicial, ligar o motor e conferir pressão/vazamentos.","Desligar, aguardar estabilização e ajustar nível.","Zerar lembrete de manutenção quando aplicável."],checks:["Nível final","Ausência de vazamentos","Pressão/luz de óleo","Especificação do lubrificante"]},
    {re:/pastilhas|discos? de freio|pin[cç]a de freio/i,title:"Serviço de freio a disco",tools:["recuador de pistão","torquímetro","paquímetro/micrômetro","limpador de freio"],steps:["Elevar o veículo, remover roda e inspecionar conjunto.","Medir disco e verificar empeno/desgaste conforme especificação.","Remover pinça/pastilhas sem deixar a pinça pendurada pela mangueira.","Inspecionar guias, coifas, pistão e flexível.","Recuar pistão pelo método correto e instalar componentes.","Aplicar lubrificação somente nos pontos permitidos.","Apertar fixações com torque correto e montar roda.","Bombear o pedal antes de movimentar o veículo e realizar teste de frenagem."],checks:["Espessura do disco/pastilha","Livre movimento das guias","Pedal firme","Ausência de vazamento/ruído"]},
    {re:/sangria|fluido de freio/i,title:"Sangria / troca do fluido de freio",tools:["equipamento de sangria","chave de sangrador","fluido homologado"],steps:["Confirmar especificação do fluido e sequência de sangria do veículo.","Proteger pintura e manter reservatório abastecido.","Sangrar cada circuito seguindo sequência correta.","Evitar entrada de ar e contaminação do fluido.","Quando ABS exigir, executar rotina de sangria via scanner.","Ajustar nível e testar pedal com motor desligado e ligado.","Verificar vazamentos em conexões e rodas."],checks:["Pedal firme","Fluido limpo e sem bolhas","Nível correto","Ausência de vazamentos"]},
    {re:/amortecedor|mola dianteira|coxim.*amortecedor/i,title:"Serviço de conjunto McPherson/suspensão",tools:["compressor de mola homologado","torquímetro","soquetes/chaves","elevador"],steps:["Inspecionar folgas e registrar posição dos componentes.","Elevar o veículo e remover a roda.","Desconectar fixações necessárias, chicotes/suportes e bieleta quando aplicável.","Remover conjunto do amortecedor.","Compressor a mola com ferramenta adequada antes de soltar porca superior.","Substituir/inspecionar amortecedor, coxim, rolamento, batente e coifa.","Montar respeitando posição e torques.","Instalar no veículo, apertar roda e realizar alinhamento quando necessário."],checks:["Assentamento da mola","Torques","Ausência de folga/ruído","Geometria/alinhamento"]},
    {re:/bucha.*barra estabilizadora|bieleta|piv[oô]|bandeja/i,title:"Serviço de suspensão dianteira",tools:["elevador","torquímetro","extrator/saca-pivô","soquetes/chaves"],steps:["Confirmar folga/ruído e lado afetado.","Elevar e apoiar o veículo.","Remover componentes que impeçam acesso.","Desmontar a peça evitando esforço em mangueiras/chicotes.","Instalar peça correta pela aplicação/VIN e posicionar buchas na posição de trabalho quando necessário.","Aplicar torques com suspensão na condição especificada pelo fabricante.","Verificar alinhamento após o serviço quando aplicável."],checks:["Folgas eliminadas","Torques","Buchas sem pré-carga indevida","Alinhamento"]},
    {re:/alternador|sistema de carga/i,title:"Diagnóstico / serviço do alternador",tools:["multímetro","alicate amperímetro","scanner","testador de bateria"],steps:["Testar bateria antes do sistema de carga.","Inspecionar correia, tensionador, cabos e aterramentos.","Medir tensão de carga em lenta e sob consumidores.","Medir queda de tensão nos cabos positivo e negativo.","Avaliar ripple/ondulação quando possível.","Se houver remoção, desconectar bateria e retirar alternador conforme acesso.","Após montagem, repetir teste de carga."],checks:["Tensão de carga","Queda de tensão","Ripple","Condição da bateria"]},
    {re:/motor de partida|sistema de partida|bendix/i,title:"Diagnóstico / serviço de partida",tools:["multímetro","alicate amperímetro","testador de bateria","soquetes/chaves"],steps:["Confirmar estado de carga e CCA da bateria.","Medir tensão durante a partida.","Executar quedas de tensão em positivo e aterramento.","Verificar comando do automático/solenoide.","Medir corrente de partida quando possível.","Se remover o motor de partida, desconectar bateria e identificar cabos.","Revisar Bendix, automático, escovas, induzido e buchas conforme necessidade.","Reinstalar e repetir medições."],checks:["Tensão durante partida","Corrente","Queda de tensão","Engrenamento e ruído"]},
    {re:/rede CAN|m[oó]dulo eletr[oô]nico|scanner|leitura de falhas|par[aâ]metros em tempo real/i,title:"Diagnóstico eletrônico",tools:["scanner automotivo","multímetro","osciloscópio quando necessário","diagramas elétricos"],steps:["Confirmar queixa do cliente e tensão da bateria.","Executar varredura completa dos módulos e salvar relatório inicial.","Registrar DTCs presentes/históricos antes de apagar qualquer código.","Analisar freeze frame e parâmetros relacionados.","Executar testes ativos e medições elétricas dirigidas pela hipótese de falha.","Consultar diagrama e verificar alimentação, aterramento e rede.","Corrigir a causa, apagar DTCs quando adequado e repetir varredura/teste."],checks:["DTCs e status","Parâmetros em tempo real","Alimentações/aterramentos","Comunicação de rede"]},
    {re:/ar-condicionado|compressor do ar-condicionado|recarga de g[aá]s|press[aã]o alta/i,title:"Diagnóstico / manutenção do ar-condicionado",tools:["manifold/estação de A/C","termômetro","detector de vazamento","scanner"],steps:["Identificar refrigerante e quantidade correta do veículo.","Inspecionar correia, compressor, condensador, ventiladores e conexões.","Medir pressões de alta/baixa e temperatura de saída.","Verificar acionamento elétrico do compressor e ventiladores.","Realizar teste de vazamento antes de recarga.","Recuperar o fluido existente quando necessário e executar vácuo.","Carregar por massa conforme especificação.","Reavaliar pressões, temperatura e vazamentos."],checks:["Pressão de alta/baixa","Temperatura na saída","Carga por massa","Ausência de vazamento"]},
    {re:/alinhamento|cambagem|caster|centraliza[cç][aã]o do volante/i,title:"Alinhamento / geometria",tools:["alinhador","rampa de alinhamento","calibrador","ferramentas de ajuste"],steps:["Calibrar pneus e verificar medidas/estado.","Inspecionar folgas de suspensão e direção antes de medir.","Posicionar veículo no equipamento e compensar sensores conforme fabricante.","Medir convergência, cambagem e caster.","Corrigir ângulos ajustáveis na sequência recomendada.","Centralizar volante e reapertar ajustes.","Imprimir/registrar valores antes e depois."],checks:["Volante centralizado","Ângulos dentro da especificação","Ausência de folgas","Pressões dos pneus"]},
    {re:/balanceamento/i,title:"Balanceamento de rodas",tools:["balanceadora","calibrador","torquímetro de roda"],steps:["Inspecionar pneu/roda e remover excesso de sujeira/pesos antigos.","Calibrar pneu e montar roda corretamente na balanceadora.","Inserir dimensões da roda e executar medição.","Aplicar pesos nas posições indicadas.","Repetir ciclo até atingir tolerância.","Instalar roda no veículo e aplicar torque correto."],checks:["Residual de desbalanceamento","Estado do pneu/roda","Torque das rodas"]}
  ];

  function actionSteps(name,cat){
    if(/troca|substitui/i.test(name))return ["Confirmar peça correta pela aplicação, ano, motor e VIN quando disponível.","Inspecionar o sistema antes da desmontagem e registrar condição inicial.","Desmontar os componentes necessários seguindo a sequência segura.","Comparar peça nova e removida antes da instalação.","Limpar superfícies/pontos de montagem e substituir vedações/fixadores de uso único quando aplicável.","Instalar e aplicar torques/especificações do fabricante.","Completar/ajustar fluidos ou calibrações quando necessário.",...common.finish];
    if(/diagn[oó]stico|teste|medi[cç][aã]o|verifica/i.test(name))return ["Confirmar sintoma e condições em que ocorre.","Executar inspeção visual e consulta de falhas/dados disponíveis.","Definir pontos de medição antes de desmontar peças.","Realizar teste com instrumento adequado e registrar valores.","Comparar resultados com especificação técnica do veículo.","Isolar a causa provável com teste confirmatório.","Registrar conclusão e recomendação."];
    if(/limpeza|higieniza/i.test(name))return ["Inspecionar o componente e confirmar que a limpeza é tecnicamente indicada.","Proteger componentes sensíveis e desmontar apenas o necessário.","Aplicar produto/equipamento compatível sem danificar sensores, vedações ou revestimentos.","Remover resíduos e secar quando aplicável.","Montar, realizar adaptação/reaprendizado quando necessário e testar funcionamento."];
    if(/reparo|revis[aã]o/i.test(name))return ["Confirmar sintomas e fazer avaliação inicial.","Desmontar o conjunto conforme acesso e procedimento técnico.","Limpar e inspecionar componentes, folgas, vedações e superfícies.","Substituir itens fora da especificação.","Montar com lubrificação, vedação e torques corretos.","Testar o conjunto antes da liberação."];
    return ["Confirmar a aplicação e a condição inicial do veículo.","Consultar o procedimento técnico correspondente ao sistema.","Preparar ferramentas, EPI e área de trabalho.","Executar a atividade de forma sequencial, registrando medições importantes.","Aplicar torques, fluidos e ajustes especificados para o veículo.",...common.finish];
  }

  window.getServiceProcedure=function(service){
    const name=service?.nome||"Serviço automotivo";
    const cat=service?.tipo||"Geral";
    const match=packs.find(p=>p.re.test(name));
    const tools=[...(catTools[cat]||["ferramentas manuais","torquímetro","equipamento de diagnóstico quando aplicável"]),...(match?.tools||[])];
    const uniqueTools=[...new Set(tools)];
    return {
      title:match?.title||name,
      objective:`Executar ${name.toLowerCase()} com controle de segurança, qualidade e rastreabilidade.`,
      safety:common.safety,
      steps:match?.steps||actionSteps(name,cat),
      tools:uniqueTools,
      checks:match?.checks||["Aplicação correta da peça/procedimento","Torques e ajustes conferidos","Sistema testado após o serviço","Ausência de vazamentos, folgas ou DTCs relacionados"],
      time:Number(service?.tempo||1),
      note:"Procedimento de referência. Consultar o manual técnico do veículo para torques, capacidades, fluidos, sequências, ferramentas especiais e boletins específicos."
    };
  };
})();
